version: '3'
services:
  selenoid:
    image: aerokube/selenoid:latest
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid:/etc/selenoid"
    command: ["-limit", "10", "-container-network", "hw_net"]
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./video
    networks:
      - hw_net

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - hw_net

networks:
  hw_net:
    driver: bridge